name: PorthHs
version: 0.1.0
synopsis: Porth in Haskell
description: Please see README.md
maintainer: Kyle Coffey <me@phytolizer.dev>
license: GPL
github: Phytolizer/PorthHs
category: Tools

ghc-options: -Wall -Werror
default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings
  - RecordWildCards

dependencies:
  - base >= 4.9 && < 5
  - protolude

library:
  source-dirs: src

executables:
  PorthHs:
    main: Main.hs
    source-dirs: cmd
    dependencies:
      - PorthHs
      - optparse-applicative

tests:
  tasty:
    main: Main.hs
    source-dirs: tests
    dependencies:
      - PorthHs
      - QuickCheck
      - tasty
      - tasty-hspec
